name = "AutoOffload"
uuid = "f0abef60-9ec0-11e9-27de-db6506a91768"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "0.1.0"

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
AbstractFFTs = "0.5, 1.0"
FFTW = "1.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
